/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package me.kpavlov.aimocks.openai.model.responses

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class InputMessageResource(
    // The role of the message input. One of `user`, `system`, or `developer`.
    @SerialName(value = "role") @Required val role: InputMessageResource.Role,
    // A list of one or many input items to the model, containing different content  types.
    @SerialName(value = "content") @Required val content: List<InputContent>,
    // The unique ID of the message input.
    @SerialName(value = "id") val id: String? = null,
    // The type of the message input. Always set to `message`.
    @SerialName(value = "type") val type: InputMessageResource.Type? = null,
    // The status of item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
    @SerialName(value = "status") val status: InputMessageResource.Status? = null,
) {
    /**
     * The role of the message input. One of `user`, `system`, or `developer`.
     *
     * Values: USER,SYSTEM,DEVELOPER
     */
    @Serializable
    public enum class Role(
        public val value: String,
    ) {
        @SerialName(value = "user")
        USER("user"),

        @SerialName(value = "system")
        SYSTEM("system"),

        @SerialName(value = "developer")
        DEVELOPER("developer"),
    }

    /**
     * The type of the message input. Always set to `message`.
     *
     * Values: MESSAGE
     */
    @Serializable
    public enum class Type(
        public val value: String,
    ) {
        @SerialName(value = "message")
        MESSAGE("message"),
    }

    /**
     * The status of item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
     *
     * Values: IN_PROGRESS,COMPLETED,INCOMPLETE
     */
    @Serializable
    public enum class Status(
        public val value: String,
    ) {
        @SerialName(value = "in_progress")
        IN_PROGRESS("in_progress"),

        @SerialName(value = "completed")
        COMPLETED("completed"),

        @SerialName(value = "incomplete")
        INCOMPLETE("incomplete"),
    }
}
