#  menu items
[[main]]
name = "Documentation"
weight = 2
url = "docs/"

[[main]]
  name = "API Reference"
  weight = 3
  url = "/apidocs/"

[[main]]
  name = "GitHub"
  weight = 4
  url = "https://github.com/mokksy/ai-mocks"

