/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

package dev.mokksy.aimocks.openai.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param code
 * @param message
 * @param `param`
 * @param type
 */
@Serializable
public data class Error(
    @SerialName(value = "code") @Required val code: String?,
    @SerialName(value = "message") @Required val message: String,
    @SerialName(value = "param") @Required val `param`: String?,
    @SerialName(value = "type") @Required val type: String,
)
