/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.mokksy.aimocks.openai.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A path to a file.
 *
 * @param type The type of the file path. Always `file_path`.
 * @param fileId The ID of the file.
 * @param index The index of the file in the list of files.
 */
@Serializable
public data class FilePath(
    // The type of the file path. Always `file_path`.
    @SerialName(value = "type") @Required val type: FilePath.Type,
    // The ID of the file.
    @SerialName(value = "file_id") @Required val fileId: kotlin.String,
    // The index of the file in the list of files.
    @SerialName(value = "index") @Required val index: kotlin.Int,
) {
    /**
     * The type of the file path. Always `file_path`.
     *
     * Values: FILE_PATH
     */
    @Serializable
    public enum class Type(
        public val value: kotlin.String,
    ) {
        @SerialName(value = "file_path")
        FILE_PATH("file_path"),
    }
}
