/*
 * A2ARequest.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 *
 * This was generated from A2A Schema: https://raw.githubusercontent.com/google/A2A/refs/heads/main/specification/json/a2a.json
 */
package me.kpavlov.aimocks.a2a.model

public interface A2ARequest {
    public data class A(
        val jsonrpc: String = "2.0",
        val id: Any? = null,
        val method: String = "tasks/send",
        val params: TaskSendParams,
    ) : A2ARequest {
        init {
            require(jsonrpc == "2.0") { "jsonrpc not constant value 2.0 - $jsonrpc" }
            require(method == "tasks/send") { "method not constant value tasks/send - $method" }
        }
    }
}
