/*
 * AgentSkill.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 *
 * This was generated from A2A Schema: https://raw.githubusercontent.com/google/A2A/refs/heads/main/specification/json/a2a.json
 */
package me.kpavlov.aimocks.a2a.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class AgentSkill(
    @SerialName("id")
    val id: SkillId,
    @SerialName("name")
    val name: String,
    @SerialName("description")
    val description: String? = null,
    @SerialName("tags")
    val tags: List<String>? = null,
    @SerialName("examples")
    val examples: List<String>? = null,
    @SerialName("inputModes")
    val inputModes: List<String>? = null,
    @SerialName("outputModes")
    val outputModes: List<String>? = null,
)
