/*
 * Artifact.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 *
 * This was generated from A2A Schema: https://raw.githubusercontent.com/google/A2A/refs/heads/main/specification/json/a2a.json
 */
package me.kpavlov.aimocks.a2a.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.EncodeDefault
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class Artifact(
    @SerialName("name")
    val name: String? = null,
    @SerialName("description")
    val description: String? = null,
    @Contextual
    @SerialName("parts")
    val parts: List<Part>,
    @SerialName("index")
    @EncodeDefault
    val index: Long = 0,
    @Contextual
    @SerialName("append")
    val append: Boolean? = null,
    @Contextual
    @SerialName("lastChunk")
    val lastChunk: Boolean? = null,
    @Contextual
    @SerialName("metadata")
    val metadata: Metadata? = null,
)
