/*
 * InternalError.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 *
 * This was generated from A2A Schema: https://raw.githubusercontent.com/google/A2A/refs/heads/main/specification/json/a2a.json
 */
package me.kpavlov.aimocks.a2a.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class InternalError(
    /** Error code */
    @SerialName("code")
    val code: Int = -32603,
    /** A short description of the error */
    @SerialName("message")
    val message: String = "Internal error",
    @Contextual
    @SerialName("data")
    val data: Any? = null,
) {
    init {
        require(code == -32603) { "code not constant value -32603 - $code" }
        require(
            message == "Internal error",
        ) { "message not constant value Internal error - $message" }
    }
}
