/*
 * Message.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 *
 * This was generated from A2A Schema: https://raw.githubusercontent.com/google/A2A/refs/heads/main/specification/json/a2a.json
 */
package me.kpavlov.aimocks.a2a.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class Message(
    @SerialName("role")
    val role: Role,
    @SerialName("parts")
    val parts: List<Part>,
    @Contextual
    @SerialName("metadata")
    val metadata: Metadata? = null,
) {
    @Suppress("EnumEntryName")
    @Serializable
    public enum class Role {
        user,
        agent,
    }

    public companion object {
        /**
         * Creates a new Message using the DSL builder.
         *
         * @param init The lambda to configure the message.
         * @return A new Message instance.
         */
        public fun create(init: MessageBuilder.() -> Unit): Message =
            MessageBuilder().apply(init).build()
    }
}
