/*
 * PushNotificationConfig.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 *
 * This was generated from A2A Schema: https://raw.githubusercontent.com/google/A2A/refs/heads/main/specification/json/a2a.json
 */
package me.kpavlov.aimocks.a2a.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class PushNotificationConfig(
    @SerialName("url")
    val url: String,
    @SerialName("token")
    val token: String? = null,
    @SerialName("authentication")
    val authentication: AuthenticationInfo? = null,
) {
    override fun toString(): String =
        "PushNotificationConfig(" +
            "url='$url', " +
            "authentication=$authentication, " +
            "token=${if (token != null) "[REDACTED]" else "null"}" +
            ")"

    public companion object
}
