/*
 * TaskStatus.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 *
 * This was generated from A2A Schema: https://raw.githubusercontent.com/google/A2A/refs/heads/main/specification/json/a2a.json
 */
package me.kpavlov.aimocks.a2a.model

import kotlinx.datetime.Instant
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class TaskStatus
    constructor(
        @Contextual
        @SerialName("state")
        val state: String,
        @Contextual
        @SerialName("message")
        val message: Message? = null,
        @Contextual
        @SerialName("timestamp")
        val timestamp: Instant? = null,
    ) {
        init {
            require(state in cg_array0) { "state not in enumerated values - $state" }
        }

        private companion object {
            private val cg_array0 =
                setOf(
                    "submitted",
                    "working",
                    "input-required",
                    "completed",
                    "canceled",
                    "failed",
                    "unknown",
                )
        }
    }
