/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package me.kpavlov.aimocks.openai.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * An error object returned when the model fails to generate a Response.
 *
 * @param code
 * @param message A human-readable description of the error.
 */
@Serializable
public data class ResponseError(
    @SerialName(value = "code") @Required val code: ResponseErrorCode,
    // A human-readable description of the error.
    @SerialName(value = "message") @Required val message: kotlin.String,
)
