/*
 * A2ARequest.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 *
 * This was generated from A2A Schema: https://raw.githubusercontent.com/google/A2A/refs/heads/main/specification/json/a2a.json
 */
package dev.mokksy.aimocks.a2a.model

import kotlinx.serialization.EncodeDefault
import kotlinx.serialization.SerialName

public interface A2ARequest {
    @SerialName("jsonrpc")
    @EncodeDefault
    public val jsonrpc: String
        get() = "2.0"
    public val id: RequestId?
    public val method: String
//    public val params: Any
}
