/*
 * JSONRPCRequest.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 *
 * This was generated from A2A Schema: https://raw.githubusercontent.com/google/A2A/refs/heads/main/specification/json/a2a.json
 */
package dev.mokksy.aimocks.a2a.model

import dev.mokksy.aimocks.a2a.model.serializers.RequestIdSerializer
import kotlinx.serialization.Contextual
import kotlinx.serialization.EncodeDefault
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public open class JSONRPCRequest<T>(
    @SerialName("jsonrpc")
    @EncodeDefault
    public val jsonrpc: String = "2.0",
    @SerialName("id")
    @Serializable(with = RequestIdSerializer::class)
    public open val id: RequestId? = null,
    @SerialName("method")
    public val method: String,
    @Contextual
    @SerialName("params")
    public open val params: T? = null,
) {
    init {
        require(jsonrpc == "2.0") { "jsonrpc not constant value 2.0 - $jsonrpc" }
    }

    public constructor(method: String, id: RequestId? = null, params: T? = null) : this(
        jsonrpc = "2.0",
        method = method,
        id = id,
        params = params,
    )
}
